# Generated by Django 4.1.5 on 2023-03-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yaroslav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
    ]
