# Generated by Django 4.1.5 on 2023-03-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yaroslav', '0002_alter_manufacturer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Manufacturer',
            new_name='man',
        ),
    ]
